version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: "paper"
      OPS: "Jobster01"
      MOTD: "§2§l§nCreeper!§4§l aw§6§l man"
      DIFFICULTY: "hard"
      SEED: "-2135836821937050197"
      VANILLATWEAKS_SHARECODE: x5whmK
      MEMORY: ""
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"

    ports:
      - "25565:25565"
      - "24454:24454/udp"
      - "80:8100"
    volumes:
      - ./data:/data
      - ./plugins:/plugins
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}